// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// NearbyUser defines model for NearbyUser.
type NearbyUser struct {
	// Distance Distance in meters
	Distance *float64 `json:"distance,omitempty"`
	UserId   *string  `json:"user_id,omitempty"`
}

// UpdateLocationRequest defines model for UpdateLocationRequest.
type UpdateLocationRequest struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// GetNearbyParams defines parameters for GetNearby.
type GetNearbyParams struct {
	Lat    float64  `form:"lat" json:"lat"`
	Lng    float64  `form:"lng" json:"lng"`
	Radius *float64 `form:"radius,omitempty" json:"radius,omitempty"`
}

// UpdateLocationJSONRequestBody defines body for UpdateLocation for application/json ContentType.
type UpdateLocationJSONRequestBody = UpdateLocationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Update the current user's location
	// (PUT /v1/location)
	UpdateLocation(ctx echo.Context) error
	// Get users nearby a location
	// (GET /v1/location/nearby)
	GetNearby(ctx echo.Context, params GetNearbyParams) error
	// Mark the current user as offline
	// (POST /v1/presence/offline)
	SetOffline(ctx echo.Context) error
	// Mark the current user as online
	// (POST /v1/presence/online)
	SetOnline(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UpdateLocation converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateLocation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateLocation(ctx)
	return err
}

// GetNearby converts echo context to params.
func (w *ServerInterfaceWrapper) GetNearby(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearbyParams
	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", ctx.QueryParams(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lat: %s", err))
	}

	// ------------- Required query parameter "lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lng", ctx.QueryParams(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lng: %s", err))
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", ctx.QueryParams(), &params.Radius, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter radius: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNearby(ctx, params)
	return err
}

// SetOffline converts echo context to params.
func (w *ServerInterfaceWrapper) SetOffline(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetOffline(ctx)
	return err
}

// SetOnline converts echo context to params.
func (w *ServerInterfaceWrapper) SetOnline(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetOnline(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.PUT(options.BaseURL+"/v1/location", wrapper.UpdateLocation, options.OperationMiddlewares["updateLocation"]...)
	router.GET(options.BaseURL+"/v1/location/nearby", wrapper.GetNearby, options.OperationMiddlewares["getNearby"]...)
	router.POST(options.BaseURL+"/v1/presence/offline", wrapper.SetOffline, options.OperationMiddlewares["setOffline"]...)
	router.POST(options.BaseURL+"/v1/presence/online", wrapper.SetOnline, options.OperationMiddlewares["setOnline"]...)

}
