// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DatingProfileRequestGender.
const (
	DatingProfileRequestGenderFEMALE DatingProfileRequestGender = "FEMALE"
	DatingProfileRequestGenderMALE   DatingProfileRequestGender = "MALE"
	DatingProfileRequestGenderOTHERS DatingProfileRequestGender = "OTHERS"
)

// Valid indicates whether the value is a known member of the DatingProfileRequestGender enum.
func (e DatingProfileRequestGender) Valid() bool {
	switch e {
	case DatingProfileRequestGenderFEMALE:
		return true
	case DatingProfileRequestGenderMALE:
		return true
	case DatingProfileRequestGenderOTHERS:
		return true
	default:
		return false
	}
}

// Defines values for DatingProfileRequestInterestedIn.
const (
	DatingProfileRequestInterestedInBOTH   DatingProfileRequestInterestedIn = "BOTH"
	DatingProfileRequestInterestedInFEMALE DatingProfileRequestInterestedIn = "FEMALE"
	DatingProfileRequestInterestedInMALE   DatingProfileRequestInterestedIn = "MALE"
)

// Valid indicates whether the value is a known member of the DatingProfileRequestInterestedIn enum.
func (e DatingProfileRequestInterestedIn) Valid() bool {
	switch e {
	case DatingProfileRequestInterestedInBOTH:
		return true
	case DatingProfileRequestInterestedInFEMALE:
		return true
	case DatingProfileRequestInterestedInMALE:
		return true
	default:
		return false
	}
}

// Defines values for DatingProfileRequestRelationshipGoal.
const (
	CASUAL  DatingProfileRequestRelationshipGoal = "CASUAL"
	SERIOUS DatingProfileRequestRelationshipGoal = "SERIOUS"
)

// Valid indicates whether the value is a known member of the DatingProfileRequestRelationshipGoal enum.
func (e DatingProfileRequestRelationshipGoal) Valid() bool {
	switch e {
	case CASUAL:
		return true
	case SERIOUS:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseRole.
const (
	DATINGONLY UserResponseRole = "DATING_ONLY"
	JOBSEEKER  UserResponseRole = "JOB_SEEKER"
	POWERUSER  UserResponseRole = "POWER_USER"
	SOCIALONLY UserResponseRole = "SOCIAL_ONLY"
)

// Valid indicates whether the value is a known member of the UserResponseRole enum.
func (e UserResponseRole) Valid() bool {
	switch e {
	case DATINGONLY:
		return true
	case JOBSEEKER:
		return true
	case POWERUSER:
		return true
	case SOCIALONLY:
		return true
	default:
		return false
	}
}

// AddPhotoRequest defines model for AddPhotoRequest.
type AddPhotoRequest struct {
	IsPrimary *bool  `json:"is_primary,omitempty"`
	S3Url     string `json:"s3_url"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string              `json:"token,omitempty"`
	User  *UserProfileResponse `json:"user,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	AvatarUrl   *string             `json:"avatar_url,omitempty"`
	Bio         *string             `json:"bio,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Phone       *string             `json:"phone,omitempty"`
}

// DatingProfileRequest defines model for DatingProfileRequest.
type DatingProfileRequest struct {
	BirthDate        openapi_types.Date                    `json:"birth_date"`
	Gender           DatingProfileRequestGender            `json:"gender"`
	HeightCm         *int                                  `json:"height_cm,omitempty"`
	InterestedIn     DatingProfileRequestInterestedIn      `json:"interested_in"`
	RelationshipGoal *DatingProfileRequestRelationshipGoal `json:"relationship_goal,omitempty"`
}

// DatingProfileRequestGender defines model for DatingProfileRequest.Gender.
type DatingProfileRequestGender string

// DatingProfileRequestInterestedIn defines model for DatingProfileRequest.InterestedIn.
type DatingProfileRequestInterestedIn string

// DatingProfileRequestRelationshipGoal defines model for DatingProfileRequest.RelationshipGoal.
type DatingProfileRequestRelationshipGoal string

// DatingProfileResponse defines model for DatingProfileResponse.
type DatingProfileResponse struct {
	BirthDate        *openapi_types.Date `json:"birth_date,omitempty"`
	Gender           *string             `json:"gender,omitempty"`
	HeightCm         *int                `json:"height_cm,omitempty"`
	InterestedIn     *string             `json:"interested_in,omitempty"`
	RelationshipGoal *string             `json:"relationship_goal,omitempty"`
	UpdatedAt        *time.Time          `json:"updated_at,omitempty"`
}

// DeleteUserResponse defines model for DeleteUserResponse.
type DeleteUserResponse struct {
	Email   *string `json:"email,omitempty"`
	Id      *string `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	Limit *int            `json:"limit,omitempty"`
	Page  *int            `json:"page,omitempty"`
	Total *int            `json:"total,omitempty"`
	Users *[]UserResponse `json:"users,omitempty"`
}

// PhotoResponse defines model for PhotoResponse.
type PhotoResponse struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	IsPrimary *bool               `json:"is_primary,omitempty"`
	S3Url     *string             `json:"s3_url,omitempty"`
	SortOrder *int                `json:"sort_order,omitempty"`
}

// ProfileRequest defines model for ProfileRequest.
type ProfileRequest struct {
	AvatarUrl   *string `json:"avatar_url,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	AvatarUrl   *string    `json:"avatar_url,omitempty"`
	Bio         *string    `json:"bio,omitempty"`
	DisplayName *string    `json:"display_name,omitempty"`
	Id          *string    `json:"id,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	UserId      *string    `json:"user_id,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Phone *string              `json:"phone,omitempty"`
}

// UserProfileResponse defines model for UserProfileResponse.
type UserProfileResponse struct {
	AvatarUrl *string    `json:"avatar_url,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt   *time.Time        `json:"created_at,omitempty"`
	Email       *string           `json:"email,omitempty"`
	Id          *string           `json:"id,omitempty"`
	IsOnboarded *bool             `json:"is_onboarded,omitempty"`
	Phone       *string           `json:"phone,omitempty"`
	Profile     *ProfileResponse  `json:"profile,omitempty"`
	Role        *UserResponseRole `json:"role,omitempty"`
	UpdatedAt   *time.Time        `json:"updated_at,omitempty"`
}

// UserResponseRole defines model for UserResponse.Role.
type UserResponseRole string

// WorkerProfileRequest defines model for WorkerProfileRequest.
type WorkerProfileRequest struct {
	HourlyRate  *float32  `json:"hourly_rate,omitempty"`
	IsAvailable *bool     `json:"is_available,omitempty"`
	Skills      *[]string `json:"skills,omitempty"`
}

// WorkerProfileResponse defines model for WorkerProfileResponse.
type WorkerProfileResponse struct {
	CompletedJobsCount *int       `json:"completed_jobs_count,omitempty"`
	HourlyRate         *float32   `json:"hourly_rate,omitempty"`
	IsAvailable        *bool      `json:"is_available,omitempty"`
	RatingAvg          *float32   `json:"rating_avg,omitempty"`
	Skills             *[]string  `json:"skills,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	// Code Authorization code from Google
	Code string `form:"code" json:"code"`

	// State State token for CSRF protection
	State string `form:"state" json:"state"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Page Page number (1-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Items per page (max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// UpdateDatingProfileJSONRequestBody defines body for UpdateDatingProfile for application/json ContentType.
type UpdateDatingProfileJSONRequestBody = DatingProfileRequest

// AddPhotoJSONRequestBody defines body for AddPhoto for application/json ContentType.
type AddPhotoJSONRequestBody = AddPhotoRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = ProfileRequest

// UpdateWorkerProfileJSONRequestBody defines body for UpdateWorkerProfile for application/json ContentType.
type UpdateWorkerProfileJSONRequestBody = WorkerProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Handle Google OAuth callback
	// (GET /v1/auth/google/callback)
	GoogleCallback(ctx echo.Context, params GoogleCallbackParams) error
	// Initiate Google OAuth login
	// (GET /v1/auth/google/login)
	GoogleLogin(ctx echo.Context) error
	// Get a user by ID (internal service-to-service, includes profile)
	// (GET /v1/internal/users/{id})
	GetUserByIdInternal(ctx echo.Context, id string) error
	// List users with pagination
	// (GET /v1/users)
	ListUsers(ctx echo.Context, params ListUsersParams) error
	// Create a new user with optional universal profile
	// (POST /v1/users)
	CreateUser(ctx echo.Context) error
	// Delete a user and all associated profiles
	// (DELETE /v1/users/{id})
	DeleteUser(ctx echo.Context, id string) error
	// Get a user by ID (includes universal profile)
	// (GET /v1/users/{id})
	GetUserById(ctx echo.Context, id string) error
	// Update user identity fields
	// (PUT /v1/users/{id})
	UpdateUser(ctx echo.Context, id string) error
	// Delete the dating profile for a user
	// (DELETE /v1/users/{id}/dating-profile)
	DeleteDatingProfile(ctx echo.Context, id string) error
	// Get the dating profile for a user
	// (GET /v1/users/{id}/dating-profile)
	GetDatingProfile(ctx echo.Context, id string) error
	// Create or update the dating profile (upsert)
	// (PUT /v1/users/{id}/dating-profile)
	UpdateDatingProfile(ctx echo.Context, id string) error
	// List all profile photos for a user
	// (GET /v1/users/{id}/photos)
	ListPhotos(ctx echo.Context, id string) error
	// Add a new profile photo
	// (POST /v1/users/{id}/photos)
	AddPhoto(ctx echo.Context, id string) error
	// Delete a profile photo
	// (DELETE /v1/users/{id}/photos/{photoId})
	DeletePhoto(ctx echo.Context, id string, photoId openapi_types.UUID) error
	// Set a photo as the primary profile photo
	// (PUT /v1/users/{id}/photos/{photoId}/primary)
	SetPrimaryPhoto(ctx echo.Context, id string, photoId openapi_types.UUID) error
	// Get the universal profile for a user
	// (GET /v1/users/{id}/profile)
	GetProfile(ctx echo.Context, id string) error
	// Create or update the universal profile (upsert)
	// (PUT /v1/users/{id}/profile)
	UpdateProfile(ctx echo.Context, id string) error
	// Delete the worker profile for a user
	// (DELETE /v1/users/{id}/worker-profile)
	DeleteWorkerProfile(ctx echo.Context, id string) error
	// Get the worker/job-seeker profile
	// (GET /v1/users/{id}/worker-profile)
	GetWorkerProfile(ctx echo.Context, id string) error
	// Create or update the worker profile (upsert)
	// (PUT /v1/users/{id}/worker-profile)
	UpdateWorkerProfile(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GoogleCallback converts echo context to params.
func (w *ServerInterfaceWrapper) GoogleCallback(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", ctx.QueryParams(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GoogleCallback(ctx, params)
	return err
}

// GoogleLogin converts echo context to params.
func (w *ServerInterfaceWrapper) GoogleLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GoogleLogin(ctx)
	return err
}

// GetUserByIdInternal converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserByIdInternal(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserByIdInternal(ctx, id)
	return err
}

// ListUsers converts echo context to params.
func (w *ServerInterfaceWrapper) ListUsers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUsers(ctx, params)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUserById converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserById(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// DeleteDatingProfile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDatingProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDatingProfile(ctx, id)
	return err
}

// GetDatingProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetDatingProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDatingProfile(ctx, id)
	return err
}

// UpdateDatingProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDatingProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDatingProfile(ctx, id)
	return err
}

// ListPhotos converts echo context to params.
func (w *ServerInterfaceWrapper) ListPhotos(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPhotos(ctx, id)
	return err
}

// AddPhoto converts echo context to params.
func (w *ServerInterfaceWrapper) AddPhoto(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddPhoto(ctx, id)
	return err
}

// DeletePhoto converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePhoto(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "photoId" -------------
	var photoId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "photoId", ctx.Param("photoId"), &photoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter photoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeletePhoto(ctx, id, photoId)
	return err
}

// SetPrimaryPhoto converts echo context to params.
func (w *ServerInterfaceWrapper) SetPrimaryPhoto(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "photoId" -------------
	var photoId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "photoId", ctx.Param("photoId"), &photoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter photoId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetPrimaryPhoto(ctx, id, photoId)
	return err
}

// GetProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProfile(ctx, id)
	return err
}

// UpdateProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProfile(ctx, id)
	return err
}

// DeleteWorkerProfile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorkerProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteWorkerProfile(ctx, id)
	return err
}

// GetWorkerProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkerProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorkerProfile(ctx, id)
	return err
}

// UpdateWorkerProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateWorkerProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateWorkerProfile(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/v1/auth/google/callback", wrapper.GoogleCallback, options.OperationMiddlewares["googleCallback"]...)
	router.GET(options.BaseURL+"/v1/auth/google/login", wrapper.GoogleLogin, options.OperationMiddlewares["googleLogin"]...)
	router.GET(options.BaseURL+"/v1/internal/users/:id", wrapper.GetUserByIdInternal, options.OperationMiddlewares["getUserByIdInternal"]...)
	router.GET(options.BaseURL+"/v1/users", wrapper.ListUsers, options.OperationMiddlewares["listUsers"]...)
	router.POST(options.BaseURL+"/v1/users", wrapper.CreateUser, options.OperationMiddlewares["createUser"]...)
	router.DELETE(options.BaseURL+"/v1/users/:id", wrapper.DeleteUser, options.OperationMiddlewares["deleteUser"]...)
	router.GET(options.BaseURL+"/v1/users/:id", wrapper.GetUserById, options.OperationMiddlewares["getUserById"]...)
	router.PUT(options.BaseURL+"/v1/users/:id", wrapper.UpdateUser, options.OperationMiddlewares["updateUser"]...)
	router.DELETE(options.BaseURL+"/v1/users/:id/dating-profile", wrapper.DeleteDatingProfile, options.OperationMiddlewares["deleteDatingProfile"]...)
	router.GET(options.BaseURL+"/v1/users/:id/dating-profile", wrapper.GetDatingProfile, options.OperationMiddlewares["getDatingProfile"]...)
	router.PUT(options.BaseURL+"/v1/users/:id/dating-profile", wrapper.UpdateDatingProfile, options.OperationMiddlewares["updateDatingProfile"]...)
	router.GET(options.BaseURL+"/v1/users/:id/photos", wrapper.ListPhotos, options.OperationMiddlewares["listPhotos"]...)
	router.POST(options.BaseURL+"/v1/users/:id/photos", wrapper.AddPhoto, options.OperationMiddlewares["addPhoto"]...)
	router.DELETE(options.BaseURL+"/v1/users/:id/photos/:photoId", wrapper.DeletePhoto, options.OperationMiddlewares["deletePhoto"]...)
	router.PUT(options.BaseURL+"/v1/users/:id/photos/:photoId/primary", wrapper.SetPrimaryPhoto, options.OperationMiddlewares["setPrimaryPhoto"]...)
	router.GET(options.BaseURL+"/v1/users/:id/profile", wrapper.GetProfile, options.OperationMiddlewares["getProfile"]...)
	router.PUT(options.BaseURL+"/v1/users/:id/profile", wrapper.UpdateProfile, options.OperationMiddlewares["updateProfile"]...)
	router.DELETE(options.BaseURL+"/v1/users/:id/worker-profile", wrapper.DeleteWorkerProfile, options.OperationMiddlewares["deleteWorkerProfile"]...)
	router.GET(options.BaseURL+"/v1/users/:id/worker-profile", wrapper.GetWorkerProfile, options.OperationMiddlewares["getWorkerProfile"]...)
	router.PUT(options.BaseURL+"/v1/users/:id/worker-profile", wrapper.UpdateWorkerProfile, options.OperationMiddlewares["updateWorkerProfile"]...)

}
