// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SwipeRequestDirection.
const (
	Left  SwipeRequestDirection = "left"
	Right SwipeRequestDirection = "right"
)

// Valid indicates whether the value is a known member of the SwipeRequestDirection enum.
func (e SwipeRequestDirection) Valid() bool {
	switch e {
	case Left:
		return true
	case Right:
		return true
	default:
		return false
	}
}

// DiscoverProfile defines model for DiscoverProfile.
type DiscoverProfile struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Bio       *string `json:"bio,omitempty"`
	Id        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// Match defines model for Match.
type Match struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	User1Id   *string    `json:"user1_id,omitempty"`
	User2Id   *string    `json:"user2_id,omitempty"`
}

// SwipeRequest defines model for SwipeRequest.
type SwipeRequest struct {
	Direction SwipeRequestDirection `json:"direction"`
	TargetId  string                `json:"target_id"`
}

// SwipeRequestDirection defines model for SwipeRequest.Direction.
type SwipeRequestDirection string

// SwipeResponse defines model for SwipeResponse.
type SwipeResponse struct {
	MatchId *string `json:"match_id,omitempty"`
	Matched *bool   `json:"matched,omitempty"`
}

// SwipeJSONRequestBody defines body for Swipe for application/json ContentType.
type SwipeJSONRequestBody = SwipeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get discoverable profiles for swiping
	// (GET /v1/discover)
	GetDiscover(ctx echo.Context) error
	// Get a match by ID (internal)
	// (GET /v1/internal/matches/{id})
	GetMatchById(ctx echo.Context, id string) error
	// Get all matches for the current user
	// (GET /v1/matches)
	GetMatches(ctx echo.Context) error
	// Record a swipe action (left or right)
	// (POST /v1/swipe)
	Swipe(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetDiscover converts echo context to params.
func (w *ServerInterfaceWrapper) GetDiscover(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDiscover(ctx)
	return err
}

// GetMatchById converts echo context to params.
func (w *ServerInterfaceWrapper) GetMatchById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMatchById(ctx, id)
	return err
}

// GetMatches converts echo context to params.
func (w *ServerInterfaceWrapper) GetMatches(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMatches(ctx)
	return err
}

// Swipe converts echo context to params.
func (w *ServerInterfaceWrapper) Swipe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Swipe(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/v1/discover", wrapper.GetDiscover, options.OperationMiddlewares["getDiscover"]...)
	router.GET(options.BaseURL+"/v1/internal/matches/:id", wrapper.GetMatchById, options.OperationMiddlewares["getMatchById"]...)
	router.GET(options.BaseURL+"/v1/matches", wrapper.GetMatches, options.OperationMiddlewares["getMatches"]...)
	router.POST(options.BaseURL+"/v1/swipe", wrapper.Swipe, options.OperationMiddlewares["swipe"]...)

}
