// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for PresenceStatus.
const (
	Away    PresenceStatus = "away"
	Offline PresenceStatus = "offline"
	Online  PresenceStatus = "online"
)

// Valid indicates whether the value is a known member of the PresenceStatus enum.
func (e PresenceStatus) Valid() bool {
	switch e {
	case Away:
		return true
	case Offline:
		return true
	case Online:
		return true
	default:
		return false
	}
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	MatchId   *string    `json:"match_id,omitempty"`
	User1Id   *string    `json:"user1_id,omitempty"`
	User2Id   *string    `json:"user2_id,omitempty"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	MatchId *string `json:"match_id,omitempty"`
	UserId  string  `json:"user_id"`
}

// Message defines model for Message.
type Message struct {
	Content        *string    `json:"content,omitempty"`
	ConversationId *string    `json:"conversation_id,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Id             *string    `json:"id,omitempty"`
	SenderId       *string    `json:"sender_id,omitempty"`
}

// Presence defines model for Presence.
type Presence struct {
	LastSeen *time.Time      `json:"last_seen,omitempty"`
	Status   *PresenceStatus `json:"status,omitempty"`
	UserId   *string         `json:"user_id,omitempty"`
}

// PresenceStatus defines model for Presence.Status.
type PresenceStatus string

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Content string `json:"content"`
}

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`
}

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all conversations for the current user
	// (GET /v1/conversations)
	GetConversations(ctx echo.Context) error
	// Create a new conversation between two users
	// (POST /v1/conversations)
	CreateConversation(ctx echo.Context) error
	// Get messages in a conversation
	// (GET /v1/conversations/{id}/messages)
	GetMessages(ctx echo.Context, id string, params GetMessagesParams) error
	// Send a message in a conversation
	// (POST /v1/conversations/{id}/messages)
	SendMessage(ctx echo.Context, id string) error
	// Get a user's online presence status
	// (GET /v1/presence/{userID})
	GetPresence(ctx echo.Context, userID string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetConversations converts echo context to params.
func (w *ServerInterfaceWrapper) GetConversations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetConversations(ctx)
	return err
}

// CreateConversation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateConversation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateConversation(ctx)
	return err
}

// GetMessages converts echo context to params.
func (w *ServerInterfaceWrapper) GetMessages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMessagesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", ctx.QueryParams(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter before: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMessages(ctx, id, params)
	return err
}

// SendMessage converts echo context to params.
func (w *ServerInterfaceWrapper) SendMessage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendMessage(ctx, id)
	return err
}

// GetPresence converts echo context to params.
func (w *ServerInterfaceWrapper) GetPresence(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPresence(ctx, userID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/v1/conversations", wrapper.GetConversations, options.OperationMiddlewares["getConversations"]...)
	router.POST(options.BaseURL+"/v1/conversations", wrapper.CreateConversation, options.OperationMiddlewares["createConversation"]...)
	router.GET(options.BaseURL+"/v1/conversations/:id/messages", wrapper.GetMessages, options.OperationMiddlewares["getMessages"]...)
	router.POST(options.BaseURL+"/v1/conversations/:id/messages", wrapper.SendMessage, options.OperationMiddlewares["sendMessage"]...)
	router.GET(options.BaseURL+"/v1/presence/:userID", wrapper.GetPresence, options.OperationMiddlewares["getPresence"]...)

}
